name: Crear un md5 del addons.xml

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Configura el node
      uses: actions/setup-node@v3

    - name: Descarga el repositorio de GitHub
      uses: actions/checkout@v4

    - name: Hacemos el hash
      uses: seepine/hash-files@v1
      id: get-hash
      with:
        patterns: |
          **/addons.xml

    - name: Introduce el hash en el archivo .md5
      run: echo ${{ steps.get-hash.outputs.hash }} >> addons.xml.md5

    - name: Hacemos el commit
      run: |
        git config --local user.email "rubenca13@gmail.com"
        git config --local user.name "RubencinRS"
        git commit -am "Add zip"

    - name: Subimos los cambios a GitHub
      uses: ad-m/github-push-action@master
      with:
        branch: main