name: Workflow que automatiza la creacion del md5 y del zip del repositorio de kodi

on:
  push:
    branches:
      - main

jobs:
  jobZip:
    name: Crear un zip de la carpeta repository.rubencinrs    
    runs-on: ubuntu-latest

    steps:
    - name: Descarga el repositorio de GitHub
      uses: actions/checkout@master

    - name: Crear zip del repositorio de kodi
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'repository.rubencinrs-0.0.1.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig addons.xml* index.html'

    - name: Subir el workspace como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: Build
        path: .
        retention-days: 1  

  jobMd5:
    name: Crear un md5 del addons.xml
    needs: jobZip
    runs-on: ubuntu-latest

    steps:
    - name: Configura el node
      uses: actions/setup-node@master

    - name: Descargamos el artefacto del zip
      uses: actions/download-artifact@v4
      with:
        name: Build

    - name: Hacemos el hash
      uses: seepine/hash-files@main
      id: get-hash
      with:
        patterns: |
          **/addons.xml

    - name: Introduce el hash en el archivo .md5
      run: echo ${{ steps.get-hash.outputs.hash }} > addons.xml.md5

    - name: Hacemos el commit
      run: |
        git config --local user.email "rubenca13@gmail.com"
        git config --local user.name "RubencinRS"
        git commit -am "Add zip and md5"

    - name: Subimos los cambios a GitHub
      uses: ad-m/github-push-action@master
      with:
        branch: main