name: Workflow que automatiza la creacion del zip del repositorio de kodi

on:
  push:
    branches:
      - main

jobs:
  jobZipMd5:
    name: Crear un zip de la carpeta repository.rubencinrs
    runs-on: ubuntu-latest
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents

    steps: 

    - name: Descarga el repositorio de GitHub
      uses: actions/checkout@v4

    - name: Crear zip del repositorio de kodi
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'repository.rubencinrs-0.0.1.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig addons.xml* index.html *.md *.zip '    

    - name: Hacemos el commit
      run: |
        git config --local user.email "rubenca13@gmail.com"
        git config --local user.name "RubencinRS"
        git add .
        git commit -m "Add zip and md5" -m "Descripcioneando"

    - name: Subimos los cambios a GitHub
      uses: ad-m/github-push-action@master
      with:
        branch: main