name: Crear un zip de la carpeta repository.rubencinrs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Crear zip del repositorio
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'repository.rubencinrs-0.0.1.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig addons.xml* index.html'
    - name: Commit files
        run: |
          git config --local user.email "rubenca13@gmail.com"
          git config --local user.name "RubencinRS"
          git commit -am "Add zip"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: main